/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.simondufour.hangman.ui;

import dev.simondufour.hangman.wordGenerator.WordGen;
import javax.swing.JButton;

/**
 *
 * @author Simon Dufour
 */
public class gameFrame extends javax.swing.JFrame {

    WordGen wordGen = new WordGen();
    
    /**
     * Creates new form gameFrame
     */
    public gameFrame() {
        initComponents();
        virtualKeyboard1.setEnabled(false);
        updateStatusBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetRandomWord = new javax.swing.JButton();
        txtRandomWord = new javax.swing.JTextField();
        btnAddWord = new javax.swing.JButton();
        lblTotalWords = new javax.swing.JLabel();
        virtualKeyboard1 = new dev.simondufour.hangman.ui.VirtualKeyboard();
        mbMenu = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miNewGame = new javax.swing.JMenuItem();
        miResetWordList = new javax.swing.JMenuItem();
        miQuit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miHowToPlay = new javax.swing.JMenuItem();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGetRandomWord.setText("Get random word");
        btnGetRandomWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRandomWordActionPerformed(evt);
            }
        });

        btnAddWord.setText("Add word to list");
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        lblTotalWords.setText("5 words left out of 20");
        lblTotalWords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        virtualKeyboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virtualKeyboard1ActionPerformed(evt);
            }
        });

        mFile.setText("File");

        miNewGame.setText("New game...");
        mFile.add(miNewGame);

        miResetWordList.setText("Reset word list");
        mFile.add(miResetWordList);

        miQuit.setText("Quit");
        mFile.add(miQuit);

        mbMenu.add(mFile);

        mHelp.setText("Help");

        miHowToPlay.setText("How to play...");
        mHelp.add(miHowToPlay);

        miAbout.setText("About...");
        mHelp.add(miAbout);

        mbMenu.add(mHelp);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGetRandomWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRandomWord)
                    .addComponent(btnAddWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 579, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(virtualKeyboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(txtRandomWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGetRandomWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddWord)
                .addGap(18, 18, 18)
                .addComponent(virtualKeyboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalWords))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetRandomWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRandomWordActionPerformed
        txtRandomWord.setText(wordGen.getRandomWord());
        virtualKeyboard1.setEnabled(true);
        virtualKeyboard1.reset();
        virtualKeyboard1.markAsTriggered("A");
        updateStatusBar();
    }//GEN-LAST:event_btnGetRandomWordActionPerformed

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        wordGen.addWord(txtRandomWord.getText().toUpperCase());
        updateStatusBar();
    }//GEN-LAST:event_btnAddWordActionPerformed

    private void virtualKeyboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virtualKeyboard1ActionPerformed
        System.out.println(((JButton)evt.getSource()).getText());
    }//GEN-LAST:event_virtualKeyboard1ActionPerformed

    private void updateStatusBar() {
        int count = wordGen.count();
        lblTotalWords.setText(count + " word" + (count > 1 ? "s " : " ") + "left out of " + wordGen.totalCount());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnGetRandomWord;
    private javax.swing.JLabel lblTotalWords;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miHowToPlay;
    private javax.swing.JMenuItem miNewGame;
    private javax.swing.JMenuItem miQuit;
    private javax.swing.JMenuItem miResetWordList;
    private javax.swing.JTextField txtRandomWord;
    private dev.simondufour.hangman.ui.VirtualKeyboard virtualKeyboard1;
    // End of variables declaration//GEN-END:variables
}
