/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.simondufour.hangman.ui;

import dev.simondufour.hangman.game.Hangman;
import dev.simondufour.hangman.wordGenerator.WordGen;
import javax.swing.JButton;

/**
 *
 * @author Simon Dufour
 */
public class gameFrame extends javax.swing.JFrame implements Observer {

    WordGen wordGen = new WordGen();
    Hangman hangman = new Hangman(wordGen);
    
    /**
     * Creates new form gameFrame
     */
    public gameFrame() {
        initComponents();
        virtualKeyboard1.setEnabled(false);
        updateStatusBar();
        hangman.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetRandomWord = new javax.swing.JButton();
        txtRandomWord = new javax.swing.JTextField();
        btnAddWord = new javax.swing.JButton();
        lblTotalWords = new javax.swing.JLabel();
        virtualKeyboard1 = new dev.simondufour.hangman.ui.VirtualKeyboard();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMysteryWord = new java.awt.TextField();
        btnNewGame = new javax.swing.JButton();
        mbMenu = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miNewGame = new javax.swing.JMenuItem();
        miResetWordList = new javax.swing.JMenuItem();
        miQuit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miHowToPlay = new javax.swing.JMenuItem();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGetRandomWord.setText("Get random word");
        btnGetRandomWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRandomWordActionPerformed(evt);
            }
        });

        btnAddWord.setText("Add word to list");
        btnAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWordActionPerformed(evt);
            }
        });

        lblTotalWords.setText("5 words left out of 20");
        lblTotalWords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        virtualKeyboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virtualKeyboard1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Player name: ");

        jLabel2.setText("Score:");

        txtMysteryWord.setEditable(false);
        txtMysteryWord.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        btnNewGame.setText("Start a new game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMysteryWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtScore)
                            .addComponent(txtPlayerName)))
                    .addComponent(btnNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(txtMysteryWord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mFile.setText("File");

        miNewGame.setText("New game...");
        mFile.add(miNewGame);

        miResetWordList.setText("Reset word list");
        mFile.add(miResetWordList);

        miQuit.setText("Quit");
        mFile.add(miQuit);

        mbMenu.add(mFile);

        mHelp.setText("Help");

        miHowToPlay.setText("How to play...");
        mHelp.add(miHowToPlay);

        miAbout.setText("About...");
        mHelp.add(miAbout);

        mbMenu.add(mHelp);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetRandomWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRandomWord)
                            .addComponent(btnAddWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(virtualKeyboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtRandomWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetRandomWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddWord)
                        .addGap(18, 18, 18)
                        .addComponent(virtualKeyboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalWords))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetRandomWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRandomWordActionPerformed
        txtRandomWord.setText(wordGen.getRandomWord());
        virtualKeyboard1.setEnabled(true);
        virtualKeyboard1.reset();
        updateStatusBar();
        hangman.randomScore();
    }//GEN-LAST:event_btnGetRandomWordActionPerformed

    private void btnAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWordActionPerformed
        wordGen.addWord(txtRandomWord.getText().toUpperCase());
        updateStatusBar();
    }//GEN-LAST:event_btnAddWordActionPerformed

    private void virtualKeyboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virtualKeyboard1ActionPerformed
        String letter = ((JButton)evt.getSource()).getText();
        hangman.addLetter(letter);
    }//GEN-LAST:event_virtualKeyboard1ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        hangman.startNewGame();
        virtualKeyboard1.setEnabled(true);
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void updateStatusBar() {
        int count = wordGen.count();
        lblTotalWords.setText(count + " word" + (count > 1 ? "s " : " ") + "left out of " + wordGen.totalCount());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWord;
    private javax.swing.JButton btnGetRandomWord;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTotalWords;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miHowToPlay;
    private javax.swing.JMenuItem miNewGame;
    private javax.swing.JMenuItem miQuit;
    private javax.swing.JMenuItem miResetWordList;
    private java.awt.TextField txtMysteryWord;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JTextField txtRandomWord;
    private javax.swing.JTextField txtScore;
    private dev.simondufour.hangman.ui.VirtualKeyboard virtualKeyboard1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updatePlayerName(String playerName) {
        txtPlayerName.setText(playerName);
    }

    @Override
    public void updateScore(int score) {
        txtScore.setText(String.valueOf(score));
    }
    
    @Override
    public void updateMysteryWord(String mysteryWord) {
        txtMysteryWord.setText(mysteryWord);
    }
}
